version: 2
updates:
  # Maintain dependencies for Github Actions as well as our proprietary code
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: monthly